### ISSUE TITLE
JSFL?

### ISSUE THREAD

**Issue by nuthinking** [grapefrukt/grapefrukt-export#11]
Why not using JSFL?

**Comment by grapefrukt** [comment]
Mostly personal convenience, I am not well versed in JSFL. 
It might have been a better choice, it might not have. Either way I wrote the better part of this in less time than it would have taken to read up on JSFL.

**Comment by nuthinking** [comment]
Good effort indeed! To be honest, the discipline of naming layers and using independent instances, keeps things in order. JSFL would probably give too much freedom which can easily bring to chaos. Another note is that my needs are also different. More than game sprites/sheets I might need to export a whole flash movie for something which can be better played back on other devices. Adobe AIR seems still very limited.

**Comment by oopstoons** [comment]
If you're interested in JSFL, check out my exporter https://github.com/oopstoons/shporter

It currently only exports to the Spriter format but I've been looking into other export formats.

I like the grapefrukt exporter but I needed something a little more specific so I made Shporter.

**Comment by nuthinking** [comment]
Will definitely check it out, thanks!
