### ISSUE TITLE
Is it possible to generate clip game automatically randomly 

### ISSUE THREAD

**Issue by FlashTang** [grapefrukt/grapefrukt-export#12]
Hi  grapefrukt
Is it possible to generate clip name automatically randomly 
How can I change your src , to make it do that way instead of giving names manually 
I think sprite has a default name , so no need to give it a name ?

Thanks

**Comment by grapefrukt** [comment]
The code that deals with removing unnamed instances is here, it should be easy to remove. 
https://github.com/grapefrukt/grapefrukt-export/blob/master/src/com/grapefrukt/exporter/extractors/ChildFinder.as#L77

But, be warned, the auto-naming isn't necessarily consistent between exports, so it may cause a ton of changes in your data files.
