### ISSUE TITLE
The xml export does not include the draw order

### ISSUE THREAD

**Issue by wldevries** [grapefrukt/grapefrukt-export#17]
For instance the god scores export has the layers export in the following order:
1. cloudback
2. cloudfront
3. rainbow
4. rays
5. text

The actual draw order is by my best guess the following:
1. rays
2. cloudback
3. rainbow
4. cloudfront
5. text

Either the Part or the Frame should include a draw order or z value. My understanding of Adobe Animate is limited so I wouldn't know..

**Comment by grapefrukt** [comment]
It's been ages since I touched this code, but I'm sure there's a zIndex property included in the exports. Though it's not impossible this might be broken somehow.

**Comment by wldevries** [comment]
I saw it's part of the textures xml export
