### ISSUE TITLE
Frame data missing, even though Animations seem to be found

### ISSUE THREAD

**Issue by rroc** [grapefrukt/grapefrukt-export#3]
Hello,
I am testing the export and realized from watching the help video (even though I did not hear it mentioned), that one needs to set ActionScript linkage for the used library objects.

Now I have managed to get the export running, but I still seem to have something missing as I only get the Animation names in the animations.xml, the frame counts mentioned seem also correct (in my case 16 and 40 for two animations). But I am missing the actual frame data.

The exporter does give a warning:
ChildFinder removing unnamed instance: instance10 at frame: 1 in parent: [object mushmoving]

The time line for my library symbol [named: mushmoving] is like this:

<pre>
title    | o mushing...........|o jumping..........|
control  | ........................................|
mushroom | o------>|o------->|o|o--------------->|o|
</pre>

And on the main scene I have the 

<pre><code>
...
AnimationExtractor.extract(export.animations, new mushmoving);
export.export();
</code></pre>

This is what I get in the animations.xml:
<pre>
Animations
  Animation name="jumping" frameCount="16"
  Animation name="mushing" frameCount="40"
/Animations
</pre>

**Comment by grapefrukt** [comment]
One slight drawback of the current animation extractor implementation is that it relies on all symbols being named. This means that if you're using an instance of, say, a clip named `Arm` you will need to name it `arm` (or `leftarm` or whatever seems appropriate) on all keyframes. 

Take a look at how the parts are named in the example files and I think it will be clearer. 

(I realize that this is very hard to understand for anyone who is not me, and I am sorry for that)

**Comment by rroc** [comment]
Heh! Yes, I now realized it... 

However, I moved to my own more simple solution of writing the exporter directly with the jsfl. In that way I get a nice menu item for the script and it is more convenient for the artists.
