### ISSUE TITLE
Adding a font to a texture atlas loses sheet entry.

### ISSUE THREAD

**Issue by shanestevens** [grapefrukt/grapefrukt-export#7]
Hi,

First off, incredibly useful tool, thanks for making open source! :)

I've been R&Ding the atlas exporter, which is working really well, however when adding a font to the atlas, the font image is added, but the texture sheet entry doesn't exist, so I don't know the rectangle of the font in the bitmap.

Have you seen this behaviour? What do you think is the best way around this?

Cheers,
Shane

**Comment by grapefrukt** [comment]
The font export has been a bit forgotten and missed out on the texture sheet bits, this should fix it!

**Comment by shanestevens** [comment]
Great, that fixed it :)  I now get:

<FontData atlas="0.png" top="193" right="425" bottom="361" left="169">

Thanks for the fast fix!

Cheers,
Shane
